In [21]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [22]:
df = pd.read_csv("../datasets/Student_Grades.csv")
df.head(3)

Hours  Practice  TeamWork  MidTerm  FinalExam  Scores Grade
0    2.5       0.5       0.0        2        2.3      21     C
1    5.1       1.5       0.5        4        4.9      47     B
2    3.2       1.0       0.5        3        2.9      27     C

In [23]:
y = df["Scores"]
x = df.drop(columns = ["Grade", "Scores"])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Hours      25 non-null     float64
 1   Practice   25 non-null     float64
 2   TeamWork   25 non-null     float64
 3   MidTerm    25 non-null     int64  
 4   FinalExam  25 non-null     float64
 5   Scores     25 non-null     int64  
 6   Grade      25 non-null     object 
dtypes: float64(4), int64(2), object(1)
memory usage: 1.5+ KB


In [25]:
y = y.values.astype("float32")
x = x.values.astype("float32")

In [31]:
model = Sequential()

model.add(Dense(16,activation = "relu"))
model.add(Dense(32, activation = "relu"))
model.add(Dense(32, activation = "relu"))
model.add(Dense(1))

model.compile(optimizer = "adam", loss = "mse")


In [34]:
model.fit(x,y, epochs = 150, batch_size = 16)

Epoch 1/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1178.4989
Epoch 2/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1048.1511 
Epoch 3/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 936.8591 
Epoch 4/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 858.0917
Epoch 5/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 762.4854 
Epoch 6/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 721.8862 
Epoch 7/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 570.3189
Epoch 8/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 471.2049
Epoch 9/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 384.7029 
Epoch 10/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 308.4488 
Epoch 11/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 244.3641 
Epoch 12/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 150.4800 
Epoch 13/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 113.1167
Epoch 14/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 83.8892 
Epoch 15/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/s

In [35]:
model.predict(np.array([[2.5, 0.5, 0, 2, 2.3]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


array([[22.033562]], dtype=float32)

In [36]:
model.predict(np.array([[5.1, 1.5, 0.5, 4, 4.9]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[43.84582]], dtype=float32)

In [37]:
model.predict(np.array([[3.2, 1.0, 0.5, 3.0, 2.9]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[30.158054]], dtype=float32)